<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lbo_glossaire"
 *
 * Auto generated by Extension Builder 2016-06-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Glossaire',
    'description' => 'Affichage de la liste des termes du glossaire.',
    'category' => 'plugin',
    'author' => 'Octavio Cim Jr',
    'author_email' => 'ocim@libeo.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '10.4.0-10.9.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    )
);
